"""empty message

Revision ID: 75fe264dd815
Revises: 87236c7e24ea
Create Date: 2022-10-13 19:07:52.612552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fe264dd815'
down_revision = '87236c7e24ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_number')
    # ### end Alembic commands ###
