"""empty message

Revision ID: 8118a42e8734
Revises: af765176afc3
Create Date: 2022-10-14 14:48:15.955952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8118a42e8734'
down_revision = 'af765176afc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('address_name', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'address_name')
    # ### end Alembic commands ###
