"""empty message

Revision ID: 87236c7e24ea
Revises: 7fb5dc3f8557
Create Date: 2022-10-13 19:06:35.807722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87236c7e24ea'
down_revision = '7fb5dc3f8557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
