"""empty message

Revision ID: 8ddf51d15a38
Revises: 0581c2e58484
Create Date: 2022-10-15 17:28:11.787378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ddf51d15a38'
down_revision = '0581c2e58484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'pics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('pics', postgresql.ARRAY(postgresql.BYTEA()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
