"""empty message

Revision ID: af765176afc3
Revises: 2b6047a1a882
Create Date: 2022-10-14 14:41:31.228532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af765176afc3'
down_revision = '2b6047a1a882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'complete_address',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'complete_address',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###
