"""empty message

Revision ID: c0d4131213ae
Revises: a2a414729845
Create Date: 2022-10-14 11:52:25.618881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d4131213ae'
down_revision = 'a2a414729845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=400), nullable=True),
    sa.Column('number', sa.String(length=400), nullable=True),
    sa.Column('street', sa.String(length=400), nullable=True),
    sa.Column('landmark', sa.String(length=400), nullable=True),
    sa.Column('code', sa.String(length=400), nullable=True),
    sa.Column('city', sa.String(length=400), nullable=True),
    sa.Column('district', sa.String(length=400), nullable=True),
    sa.Column('state', sa.String(length=400), nullable=True),
    sa.Column('country', sa.String(length=400), nullable=True),
    sa.Column('complete_address', sa.String(length=600), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
