"""empty message

Revision ID: c6cb4294c5e6
Revises: cb4880738c51
Create Date: 2022-10-20 12:13:34.865285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6cb4294c5e6'
down_revision = 'cb4880738c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventoryuser', sa.Column('permission', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventoryuser', 'permission')
    # ### end Alembic commands ###
