"""empty message

Revision ID: cb4880738c51
Revises: 052ccc214d1a
Create Date: 2022-10-19 15:38:25.597168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4880738c51'
down_revision = '052ccc214d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventoryuser',
    sa.Column('id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('admin_usr_name', sa.String(length=16), nullable=False),
    sa.Column('admin_mail', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('contact_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_mail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventoryuser')
    # ### end Alembic commands ###
